# Generated by Django 4.1.6 on 2023-02-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Customer ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Movie ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WishlistModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Wishlist Item ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
